update-drivers-list: fix kernel_version to avoid errors on github runners.
The github runners might use a kernel version that make `rpmspec` un-happy:

  runner@runnervmeorf1:~/work/hypervisor-dev/hypervisor-dev/drivers/8.3/srpm/qlogic-netxtreme2-alt$ rpmspec --query --qf '%{Version}-%{Release}\n'  SPECS/*.spec
  error: line 30: Invalid version (double separator '-'): 6.17.0-1010-azure: Requires: kernel-uname-r = 6.17.0-1010-azure
  error: query of specfile SPECS/qlogic-netxtreme2-alt.spec failed, can't parse

Because we don't really care about actually building against a kernel and
are just trying to infer the version-release tuple, let's fix it to avoid
the errors altogether.

Signed-off-by: Quentin Casasnovas <quentin.casasnovas@vates.tech>